# appveyor.yml - https://www.appveyor.com/docs/lang/python
---

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      PYTHON: "3.7"
      PYTHONPATH: "C:\\Python37-x64"
      TOXENV: python3.7
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      PYTHON: "3.8"
      PYTHONPATH: "C:\\Python38-x64"
      TOXENV: python3.8
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      PYTHON: "3.9"
      PYTHONPATH: "C:\\Python39-x64"
      TOXENV: python3.9
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      PYTHON: "3.10"
      PYTHONPATH: "C:\\Python310-x64"
      TOXENV: python3.10
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.7"
      TOXENV: python3.7
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.8"
      TOXENV: python3.8
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.9"
      TOXENV: python3.9
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.10"
      TOXENV: python3.10
stack: python %PYTHON%

build: false

for:
-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
        PYTHON: "3.7"
        PYTHONPATH: "C:\\Python37-x64"
        TOXENV: python3.7
    
  install:
    - "SET PATH=%PYTHONPATH%;%PYTHONPATH%\\Scripts;%PATH%"
    - "%PYTHONPATH%\\python.exe -m pip install https://onedrive.live.com/download?cid=C9974FFDBF7F1C3A%26resid=c9974ffdbf7f1c3a%252123180%26authkey=ANRN8GGmMBoWQcU"
    - "%PYTHONPATH%\\python.exe -m pip install https://onedrive.live.com/download?cid=C9974FFDBF7F1C3A%26resid=c9974ffdbf7f1c3a%252123176%26authkey=APkWJiPB84TDr8E"
    - "%PYTHONPATH%\\python.exe -m pip install https://onedrive.live.com/download?cid=C9974FFDBF7F1C3A%26resid=c9974ffdbf7f1c3a%252123167%26authkey=ABQpH76ChDCuI5M"
    - "%PYTHONPATH%\\python.exe -m pip install tox"
  test_script:
    - "%PYTHONPATH%\\python.exe -m tox"

-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
        PYTHON: "3.8"
        PYTHONPATH: "C:\\Python38-x64"
        TOXENV: python3.8 
  install:
    - "SET PATH=%PYTHONPATH%;%PYTHONPATH%\\Scripts;%PATH%"
    - "%PYTHONPATH%\\python.exe -m pip install https://onedrive.live.com/download?cid=C9974FFDBF7F1C3A%26resid=c9974ffdbf7f1c3a%252123179%26authkey=AKu8Oz6taUjTZ4I"
    - "%PYTHONPATH%\\python.exe -m pip install https://onedrive.live.com/download?cid=C9974FFDBF7F1C3A%26resid=c9974ffdbf7f1c3a%252123173%26authkey=AAa3ZIbVi3WuGQU"
    - "%PYTHONPATH%\\python.exe -m pip install https://onedrive.live.com/download?cid=C9974FFDBF7F1C3A%26resid=c9974ffdbf7f1c3a%252123170%26authkey=AAdIkUzE21OnNHs"
    - "%PYTHONPATH%\\python.exe -m pip install tox"
  test_script:
    - "%PYTHONPATH%\\python.exe -m tox"    

-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
        PYTHON: "3.9"
        PYTHONPATH: "C:\\Python39-x64"
        TOXENV: python3.9
    
  install:
    - "SET PATH=%PYTHONPATH%;%PYTHONPATH%\\Scripts;%PATH%"
    - "%PYTHONPATH%\\python.exe -m pip install https://onedrive.live.com/download?cid=C9974FFDBF7F1C3A%26resid=c9974ffdbf7f1c3a%252123177%26authkey=ANksMmOZFSriprw"
    - "%PYTHONPATH%\\python.exe -m pip install https://onedrive.live.com/download?cid=C9974FFDBF7F1C3A%26resid=c9974ffdbf7f1c3a%252123174%26authkey=APZjZ2d8YEIQseI"
    - "%PYTHONPATH%\\python.exe -m pip install https://onedrive.live.com/download?cid=C9974FFDBF7F1C3A%26resid=c9974ffdbf7f1c3a%252123169%26authkey=AJklZekr88cAeQU"
    - "%PYTHONPATH%\\python.exe -m pip install tox"
  test_script:
    - "%PYTHONPATH%\\python.exe -m tox"
    
-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
        PYTHON: "3.10"
        PYTHONPATH: "C:\\Python310-x64"
        TOXENV: python3.10
    
  install:
    - "SET PATH=%PYTHONPATH%;%PYTHONPATH%\\Scripts;%PATH%"
    - "%PYTHONPATH%\\python.exe -m pip install https://onedrive.live.com/download?cid=C9974FFDBF7F1C3A%26resid=c9974ffdbf7f1c3a%252123178%26authkey=AK7cp_Z-u-vZ9b0"
    - "%PYTHONPATH%\\python.exe -m pip install https://onedrive.live.com/download?cid=C9974FFDBF7F1C3A%26resid=c9974ffdbf7f1c3a%252123175%26authkey=ALauzZbXlTXUcbw"
    - "%PYTHONPATH%\\python.exe -m pip install https://onedrive.live.com/download?cid=C9974FFDBF7F1C3A%26resid=c9974ffdbf7f1c3a%252123168%26authkey=APui_76KFfzj68Y"
    - "%PYTHONPATH%\\python.exe -m pip install tox"
  test_script:
    - "%PYTHONPATH%\\python.exe -m tox"
    
-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
        PYTHON: "3.7"
        TOXENV: python3.7
  install:
    - sh: sudo add-apt-repository ppa:ubuntugis/ppa
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install python-numpy gdal-bin libgdal-dev
    - sh: sudo apt-get -y install python3-pip
    - pip3 install tox
  test_script:
    - sh: python3 -m tox

-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
        PYTHON: "3.8"
        TOXENV: python3.8
  install: 
    - sh: sudo add-apt-repository ppa:ubuntugis/ppa
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install python-numpy gdal-bin libgdal-dev
    - sh: sudo apt-get -y install python3-pip
    - pip3 install tox
  test_script:
    - sh: python3 -m tox

-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
        PYTHON: "3.9"
        TOXENV: python3.9
  install: 
    - sh: sudo add-apt-repository ppa:ubuntugis/ppa
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install python-numpy gdal-bin libgdal-dev
    - sh: sudo apt-get -y install python3-pip
    - pip3 install tox
  test_script:
    - sh: python3 -m tox

-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
        PYTHON: "3.10"
        TOXENV: python3.10
  install: 
    - sh: sudo add-apt-repository ppa:ubuntugis/ppa
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install python-numpy gdal-bin libgdal-dev
    - sh: sudo apt-get -y install python3-pip
    - pip3 install https://files.pythonhosted.org/packages/c5/00/29cf4f6c63271136616dc4cad7850dc8073bfa773e8a46de79820c722109/rasterio-1.3a3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
    - pip3 install tox
  test_script:
    - sh: python3 -m tox

