# appveyor.yml - https://www.appveyor.com/docs/lang/python
---
image:
  - Ubuntu

environment:
  matrix:
  # - TOXENV: py27  # https://devguide.python.org/devcycle/#end-of-life-branches
  # - TOXENV: py35
  - TOXENV: py36    # https://devguide.python.org/#status-of-python-branches
  - TOXENV: py37
  - TOXENV: py38
  - TOXENV: py39
  - TOXENV: py310

build: false

install:
  # - py --list
  # - py -m pip install --upgrade pip
  - python3 -m pip install tox

test_script:
  - python3 -m tox