# appveyor.yml - https://www.appveyor.com/docs/lang/python
---
image:
  - Ubuntu

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "$HOME/venv3.7"
      TOXENV: python3.7
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "$HOME/venv3.8.12"
      TOXENV: python3.8
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "$HOME/venv3.9.10"
      TOXENV: python3.9
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "$HOME/venv3.10.2"
      TOXENV: python3.10

build: false

for:
-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
        PYTHON: "$HOME/venv3.7"
        TOXENV: python3.7
    
  install:
    - abs_path="$(cd "$PYTHON" && pwd -P)"
    - sh: sudo update-alternatives --set python3 $abs_path
    - python3 --version
    - python3 -version
    - sh: sudo add-apt-repository ppa:ubuntugis/ppa
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install python-numpy gdal-bin libgdal-dev
    - python3 --version
    - sh: sudo apt-get -y install python3-pip
    - python3 --version
    - pip3 install tox

-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
        PYTHON: "$HOME/venv3.8.12"
        TOXENV: python3.8
  install: 
    - python3 --version
    - python3 -version
    - sh: sudo add-apt-repository ppa:ubuntugis/ppa
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install python-numpy gdal-bin libgdal-dev
    - sh: sudo apt-get -y install python3-pip
    - pip3 install tox

-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
        PYTHON: "$HOME/venv3.9.10"
        TOXENV: python3.9
  install: 
    - python3 --version
    - python3 -version
    - sh: sudo add-apt-repository ppa:ubuntugis/ppa
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install python-numpy gdal-bin libgdal-dev
    - sh: sudo apt-get -y install python3-pip
    - pip3 install tox

-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
        PYTHON: "$HOME/venv3.10.2"
        TOXENV: python3.10
  install: 
    - python3 --version
    - python3 -version
    - sh: sudo add-apt-repository ppa:ubuntugis/ppa
    - sh: sudo apt-get update
    - sh: sudo apt-get -y install python-numpy gdal-bin libgdal-dev
    - sh: sudo apt-get -y install python3-pip
    - pip3 install https://files.pythonhosted.org/packages/c5/00/29cf4f6c63271136616dc4cad7850dc8073bfa773e8a46de79820c722109/rasterio-1.3a3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
    - pip3 install tox

test_script:
  - python3 -m tox