# appveyor.yml - https://www.appveyor.com/docs/lang/python
---
stack: python 3.9
image:
  - Ubuntu

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.9"

build: false

install:
  #- pip3 install --upgrade pip
  - pip --version
  - pip install tox
  #- python3 --list

test_script:
  - python3 -m tox