# appveyor.yml - https://www.appveyor.com/docs/lang/python
---
stack: python 3.7, python 3.8, python 3.9, python 3.10
image:
  - Ubuntu

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.7"
      TOXENV: python3.7
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.8"
      TOXENV: python3.8
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.9"
      TOXENV: python3.9
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.10"
      TOXENV: python3.10

build: false

install:
  #- pip3 install --upgrade pip
  #- pip --version
  - sh: sudo add-apt-repository ppa:ubuntugis/ppa
  - sh: sudo apt-get update
  - sh: sudo apt-get install python-numpy gdal-bin libgdal-dev
  - pip install tox
  #- python3 --list

test_script:
  - python3 -m tox