# appveyor.yml - https://www.appveyor.com/docs/lang/python
---

image:
  - Ubuntu

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.7"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.8"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.9"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.10"
  #- TOXENV: py37
  #- TOXENV: py38
  #- TOXENV: py39
  #- TOXENV: py310

build: false

install:
  #- pip3 install --upgrade pip
  - pip --version
  - pip install tox
  #- python3 --list

test_script:
  - python3 -m tox