# appveyor.yml - https://www.appveyor.com/docs/lang/python
---
stack: python 3.7, python 3.8, python 3.9, python 3.10
image:
  - Ubuntu

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.7"
      TOXENV: py37
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.8"
      TOXENV: py38
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.9"
      TOXENV: py39
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.10"
      TOXENV: py310

build: false

install:
  #- pip3 install --upgrade pip
  #- pip --version
  - pip install tox
  #- python3 --list

test_script:
  - python3 -m tox