{% set data = load_setup_py_data() %}

package:
  name: remote-sensing-processor
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/simonreise/remote-sensing-processor

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy

  run:
    - python
    - numpy
    - h5py
    - tensorflow>=2.3
    - scikit-image
    - rasterio
    - pyproj
    - shapely
    - geopandas


about:
  home: