{% set pyproject = load_file_data('pyproject.toml') %}

package:
  name: remote-sensing-processor
  version: {{ pyproject.get('version') }}

source:
  path: ./..

requirements:
  build:
    - python >=3.12
    - cython
    - numpy >=1.17
  host:
    - bottleneck
    - dask
    - datasets >=4.3.0
    - geopandas
    - geocube
    - geotiepoints
    - huggingface_hub
    - libgdal
    - lightning >=2.2
    - numpy >=2
    - odc-geo >=0.4.3
    - pip
    - pydantic
    - pystac
    - python >=3.12
    - python-geotiepoints
    - pytorch >=2.2
    - rasterio >=1.4.4
    - rioxarray >=0.20
    - satpy
    - scikit-image >=0.18
    - scikit-learn >=1.0
    - segmentation-models-pytorch >=0.5.0
    - shap
    - spyndex
    - stactools
    - tensorboard
    - timm
    - torchgeo
    - torchmetrics >=1.8.1
    - torchvision >=0.17
    - transformers >=4.56.0
    - xarray-spatial
    - xbatcher
    - xgboost
  run:
    - bottleneck
    - dask
    - datasets >=4.3.0
    - geopandas
    - geocube
    - huggingface_hub
    - libgdal
    - lightning >=2.2
    - numpy >=2
    - odc-geo >=0.4.3
    - pydantic
    - pystac
    - python >=3.12
    - python-geotiepoints
    - pytorch >=2.2
    - rasterio >=1.4.4
    - rioxarray >=0.20
    - satpy
    - scikit-image >=0.18
    - scikit-learn >=1.0
    - segmentation-models-pytorch >=0.5.0
    - shap
    - spyndex
    - stactools
    - tensorboard
    - timm
    - torchgeo
    - torchmetrics >=1.8.1
    - torchvision >=0.17
    - transformers >=4.56.0
    - xarray-spatial
    - xbatcher
    - xgboost
    
build:
    noarch: python

test:
  imports:
    - remote_sensing_processor
    - remote_sensing_processor.common
    - remote_sensing_processor.dem
    - remote_sensing_processor.imagery
    - remote_sensing_processor.indices
    - remote_sensing_processor.landsat
    - remote_sensing_processor.mosaic
    - remote_sensing_processor.semantic
    - remote_sensing_processor.regression
    - remote_sensing_processor.sentinel2


about:
  home: "https://github.com/simonreise/remote-sensing-processor"
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  license_file:
  summary: "RSP is a tool for geospatial raster data processing"
  doc_url: "https://remote-sensing-processor.readthedocs.io"
  dev_url:
