package:
  name: remote-sensing-processor
  version: 0.3.0

source:
  path: ./..

build:
  noarch: python
  script: pip install . -v

requirements:
  host:
    - python >=3.12
    - pip
    - setuptools
  run:
    - bottleneck
    - dask
    - datasets >=4.3.0
    - geopandas
    - geocube
    - huggingface_hub
    - libgdal
    - lightning >=2.2
    - numpy >=2
    - odc-geo >=0.4.3
    - pydantic
    - pystac
    - python >=3.12
    - python-geotiepoints
    - pytorch >=2.2
    - rasterio >=1.4.4
    - rioxarray >=0.20
    - satpy >=0.59.0
    - scikit-image >=0.18
    - scikit-learn >=1.0
    - segmentation-models-pytorch >=0.5.0
    - shap
    - spyndex
    - stactools
    - tensorboard
    - timm
    - torchgeo >=0.9
    - torchmetrics >=1.8.1
    - torchvision >=0.17
    - transformers >=5.1.0
    - xarray-spatial
    - xbatcher >=0.3
    - xgboost

tests:
  - python:
      imports:
        - remote_sensing_processor
        - remote_sensing_processor.common
        - remote_sensing_processor.dem
        - remote_sensing_processor.imagery
        - remote_sensing_processor.indices
        - remote_sensing_processor.mosaic
        - remote_sensing_processor.segmentation.semantic
        - remote_sensing_processor.segmentation.regression

about:
  license: GPL-3.0-or-later
  summary: RSP is a tool for geospatial raster data processing and machine learning
  homepage: https://github.com/simonreise/remote-sensing-processor
  documentation: https://remote-sensing-processor.readthedocs.io